### ISSUE TITLE
Expand images in the feed

### ISSUE THREAD

**Issue by drequivalent** [ciderpunx/twitrssme#15] opened 2015-12-13 17:43 UTC
There's a lot if posts with links to images like this: pic.twitter.com/xk8XFvTd1j
May be, it's a good idea to expand them so RSS fetcher (like Owncloud) could fetch and display them.

**Comment by ciderpunx** [comment] 2016-02-02 17:35
Thanks. I think this is probably a regression will have a proper look soon.

**Comment by ciderpunx** [comment] 2016-02-08 17:47
Images are now in image tags so owncloud ought to do the right thing with them (maybe). Fancy testing it to see if it works as expected?

**Comment by drequivalent** [comment] 2016-02-19 14:37
Yep, I will soon get my OC vertical and try again. Thank you.

**Comment by ciderpunx** [comment] 2016-03-01 13:18
Closing because I reckon it is fixed. re-open if not ;-)

**Closed by ciderpunx** 2016-03-01 13:18 UTC

**Comment by 07416** [comment] 2017-02-22 16:39
Twitter images (`pbs.twimg.com/media/*`) in the feed are embedded as a tiny thumbnail and not in full size.

example tweet: https://twitter.com/bugbeargames/status/833958387691954176
TwitRSS feed for the account: https://twitrss.me/twitter_user_to_rss/?user=bugbeargames

![2017-02-22 18_38_36-bugbearentertainment on twitter_ _very soon now https___t co_qopccq6dg1_ - to](https://cloud.githubusercontent.com/assets/14923168/23221620/36f4a18c-f92e-11e6-8052-efc17aaa19d7.png)

![2017-02-22 18_36_29-twitter search _ bugbeargames - tor browser](https://cloud.githubusercontent.com/assets/14923168/23221554/124854fa-f92e-11e6-9886-86bb36c6ad78.png)

Can we get the images in the native size?

**Comment by ciderpunx** [comment] 2017-02-23 09:50
The image is sourced at the original size, it is just that the width attribute is set in the html.  The img src points to: https://pbs.twimg.com/media/C5LQqDJWEAEMBjw.jpg which is 1,200px × 675px. 

There isn't an obvious width at which to display the images, so I chose a width that should work on most modern devices.

If you'd like it displayed larger, just overwrite the width i.e. change:

`<img width="250" src="https://pbs.twimg.com/media/C5LQqDJWEAEMBjw.jpg" xml:base="https://twitrss.me/twitter_user_to_rss/?user=bugbeargames"/>`

To:
`<img width="1200" src="https://pbs.twimg.com/media/C5LQqDJWEAEMBjw.jpg" xml:base="https://twitrss.me/twitter_user_to_rss/?user=bugbeargames"/>`

Or whatever  you wish.
